version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "4000:4000"
    client:
        build:
            context: ./client
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"