import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { selectCurrentUser } from '../../redux/features/user/user-reducer'
import { useAppSelector } from '../../redux/hooks'

export interface HomeProps {}

export const Home: NextPage<HomeProps> = () => {
  const currentUser = useAppSelector(selectCurrentUser)

  console.log(currentUser)

  return (
    <div className="">
      <Head>
        <title>Expense Tracker - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  )
}

export default Home
