import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Modal from '../../components/base/Modal/Modal'
import Tabs from '../../components/base/Tabs/Tabs'
import RecentTransaction from '../../components/features/RecentTransactions/RecentTransaction'
import { useGetCurrentLoggedInUserQuery } from '../../redux/features/user/user-api'

export interface HomeProps {}

export const Home: NextPage<HomeProps> = () => {
  const { data: user, isLoading } = useGetCurrentLoggedInUserQuery({})

  if (isLoading) return <Modal show message="loading" />

  return (
    <div className="">
      <Head>
        <title>Expense Tracker - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <RecentTransaction />
    </div>
  )
}

export default Home
